name: Build the Image
on:
  workflow_dispatch

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      
      - name: Build Docker Image
        run: docker build -t my-test-app .
      
      - name: Push to Docker Hub
        env:
          d_username: ${{ vars.DOCKERHUB_USERNAME }}
        run: |
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ vars.DOCKERHUB_USERNAME }} --password-stdin
          docker tag my-app $d_username/my-test-app:v${{ github.run_number }}
          docker push $d_username/my-test-app:v${{ github.run_number }}

    
