name: Debug Deployment to GCP
on:
  workflow_dispatch

env:
  ADMIN_PROJECT_ID: "techullurgy-ci-cd"
  PROJECT_ID: "howzapp-techullurgy-full"
  PROJECT_NAME: "Howzapp Backend Full"

jobs:
  gcp-debug-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CI_CD_ADMIN_KEY }}

      - name: Setup Google CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Debug
        run: |
          gcloud organizations list
          gcloud auth list

      - name: Create New GCP Project
        run: |
          echo "Creating Project $PROJECT_ID"
          gcloud projects create $PROJECT_ID \
            --name="$PROJECT_NAME"

          echo "Linking billing account..."
          gcloud beta billing projects link $PROJECT_ID \
            --billing-account=${{ secrets.GCP_BILLING_ACCOUNT }}

      
      - name: Set project for gcloud
        run: gcloud config set project $PROJECT_ID

      - name: Enable required APIs
        run: |
          gcloud services enable compute.googleapis.com \
            iam.googleapis.com \
            cloudresourcemanager.googleapis.com
