on:
  workflow_dispatch:

jobs:
  yaml-parser:
    runs-on: ubuntu-latest
    steps:
      - name: Download yq
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Create basic Yaml file
        run: |
          cat <<EOF > temporary.yaml
          a:
            b:
              - c: abcd
              - c: wxyz
          EOF

      - name: Print a.b[0].c
        run: yq '.a.b[0].c' temporary.yaml

      - name: In-place Change of a.b[0].c
        run: yq -i '.a.b[0].c = "ijkl"' temporary.yaml
      
      - name: Print a.b[0].c
        run: yq '.a.b[0].c' temporary.yaml

      - name: In-place Change of a.b.[2].c
        run: yq -i '.a.b.[2].c = "pqrs"' temporary.yaml

      - name: Print Yaml
        run: cat temporary.yaml

      - name: Create Sample Properties
        run: |
          cat <<EOF > sample.properties
          gradlePath = /org/gradle
          # distributionUrl=123
          distributionUrl = People are awesome!
          region = US
          EOF

      - name: Change Properties file
        run: yq -i -p=props -o=props '.distributionUrl = "We are very Welcoming in nature"' sample.properties

      - name: Print Properties file
        run: cat sample.properties
